### ISSUE TITLE
Create script to clone and build usd without Python or Qt

### ISSUE THREAD

**Issue by jacques-gasselin** [jacques-gasselin/usdview-native#1]
USD is one of the dependencies of the project so we need to pull tagged releases to compile against. We want it in a local folder so we don't clobber anything installed.

**Comment by superfunc** [comment]
The essence of this, or at least how I do it locally is:

```bash
mkdir -p build/inst
cd build
python ../usd/build_scripts/build.py --no-tests --no-python --build-monolithic
```

**Comment by superfunc** [comment]
Further note, will need to add:

`usd_build/inst/lib @executable_path/../Frameworks` to _Runtime Search Paths_
`usd_build/inst/lib` to _Library Search Path_
`-lusd_ms -lboost_atomic -lboost_system` to _Other Linker Flags_

**Comment by jacques-gasselin** [comment]
The download and install into a deps folder is in 9e34d9b. I suppose we should fix up the xcodeproj paths once we reference the USD apis.

**Comment by superfunc** [comment]
We'll probably want to have built out libs actually checked in alongside the source, this would make CI faster, and that source is only going to change every few months when bumping USD version.

**Comment by jacques-gasselin** [comment]
That seems fair. I'll see if I can have deps be a local dir that is gitignored and a lib folder for the macOS USD libs.

**Comment by meshula** [comment]
I wonder if this might be the right approach: https://github.com/VictorYudin/saturn  Victor has set AppVeyor up to do the builds and create artifacts.

**Comment by superfunc** [comment]
Yeah, I figure we may do something similar when tackling #4
