### ISSUE TITLE
Symbols starting with underscore are reserved in the global scope

### ISSUE THREAD

**Issue by meshula** [jacques-gasselin/usdview-native#19]
https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

Easy enough to accomodate by adding a namespace to usd.h’s methods.

**Comment by superfunc** [comment]
Yep, old habits die hard, will fix :)

Instead of wrapping them in a namespace I'll just set a different prefix.
