### ISSUE TITLE
is there crossover with the usd-qt project?

### ISSUE THREAD

**Issue by meshula** [jacques-gasselin/usdview-native#20]
Luma Pictures has got a bunch of cpp files here 

https://github.com/LumaPictures/usd-qt/tree/master/pxr/usdQt

For wrapping USD objects and utilities for display in Qt. I’m thinking of leveraging that work for Imgui wrapping. I wonder if their cpp work might be helpful here as well?

**Comment by superfunc** [comment]
It depends how disentangled they are from Qt bits. If they are then there could be a crossover, but we would still need to expose a C-API to bind into Swift. Ideally, I'd like to have a shared usd-c-ffi for us to all lean on.

**Comment by superfunc** [comment]
The other big no-no, for me at least, is a dependence on Python in usd-qt.

**Comment by meshula** [comment]
My first pass suggests it's a structural issue with their codebase, they've mixed their cpp & py together. The cpp files don't seem to directly reference Python or Qt, or at least I haven't found where they do yet.

I agree a C ffi would be nicest; Jeremy's SWIG scripts for C# show a possible implementation strategy (and he's done all the heavy lifting already).

That said, the usd-qt C++ files don't wrap USD per se; they are user interface related helper functions that bag up queries and operations that UIs need (traversals to populate treeviews for example) that are otherwise tedious to code to the USD API.

I spoke with them at Siggraph, they are open to splitting the helpers out into a separate library for use outside of the Py/Qt world.
