### ISSUE TITLE
CI Setup

### ISSUE THREAD

**Issue by superfunc** [jacques-gasselin/usdview-native#4]
Opening this up to get CI into a good place.

Things to do:

- [x] Setup WIP Bot (https://github.com/apps/wip) useful for discussing progress on a change
- [x] Setup Travis CI (https://github.com/apps/travis-ci)
- [x] Setup Basic Linter (https://github.com/realm/SwiftLint)

**Comment by superfunc** [comment]
Note that the owner of the repo @jacques-gasselin will have to do 1-2 since I don't have access.

**Comment by jacques-gasselin** [comment]
1 and 2 are installed. Nothing configured over the defaults yet.

**Comment by superfunc** [comment]
While we're here, I'll also look to muffle the USD warnings from the swift app.

**Comment by jacques-gasselin** [comment]
Is the linter there? We have clang format and swift format in the pre-commit hooks.

**Comment by superfunc** [comment]
Oops, yeah, didn't get moved over from my private git hooks. Added in above commit.

**Comment by superfunc** [comment]
~~Note that in the above commit I needed to update some of the newly checked in files. 
You'll need to run `.buildScripts/dev-setup` to pick up the git hook which checks formatting etc.~~

Nope, I was wrong move along 😄

**Comment by superfunc** [comment]
I'll leave this open for @jacques-gasselin to add swiftlint and the formatters into the xcode build
